kndoll:
  profile: I'm stg - update
  comment: stg config - update
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: kndoll
    password: doll
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
